//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessPartners
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialType
    {
        public int MaterialTypeID { get; set; }
        public string MaterialTypeName { get; set; }
        public Nullable<decimal> DefectRate { get; set; }
    }
}
